spring:
  application:
    name: spring-boot-redis-cache

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cache:
    type: redis

  data:
    redis:
      host: ${HOST}}
      port: ${PORT}
